### ISSUE TITLE
"Unknown option" when trying to specify scheduled task

### ISSUE THREAD

**Issue by pauln** [micaherne/moodle-local_nagios#1]
The script doesn't appear to handle service-specific parameters - attempting to specify additional parameters (such as the "task" parameter for the `scheduled_task` service) results in messages such as:
`Unknown option: task`

I've had a go at hacking in support (in a local working copy), by way of an additional "param" hash-value option, which works but seems a bit clumsy for a couple of reasons:
- `-p` is already taken by `-plugin`, so using `-param` means that both need to be specified in full as `p` becomes ambiguous; perhaps "options" would work as an alternative (giving `-o`)
- If we continue using the "Moodle-style parameter passing", we end up with things like `-o=task='\\core\\task\\events_cron_task'` - having `=` twice in the one parameter feels a bit icky, though it works fine

I'm happy to submit a pull request to implement this, if you're happy with the slightly cludgy syntax (and clarify whether you'd rather it be `-option` or `-param`) - though I'm by no means a Perl expert, so I can't promise it'll be perfect.

**Comment by micaherne** [comment]
Hi Paul, I take it you're using the /script/check_moodle script? I think that should have been removed, and the /cli/check_moodle script used in place of it. 

Sorry about that - I should have removed that script and updated the documentation! I'll do that instead of merging your pull request if you don't mind.

The new script (which is basically a very thin executable shell script in PHP round the main check_moodle.php one) takes service parameters. We have it working in production with command definitions like this:

```
command[check_moodle_strathenrol_sync]=/path/to/local/nagios/cli/check_moodle -p=local_nagios -s=scheduled_task --task=\\local_strathenrol\\task\\sync -w93600 -c=100800
```

**Comment by micaherne** [comment]
That's the old Perl plugin removed and the README updated. Thanks for bringing this to my attention!

**Comment by pauln** [comment]
Fantastic, thanks - I'd thought I must surely be missing something, but I didn't expect it to be an entire script!
